### ISSUE TITLE
noob cosmologists' questions

### ISSUE THREAD

**Issue by etozhepizteh** [pec27/smerfs#2]
Did You produce the 3D visualisation (one on the preview) with smerf or was it done in another way? I can not fathom out how to change the exponent of lambda in the C_lambda (it is 4 in the example) .
Although these questions are rather stupid, could You, please, give a hint, if it is not difficult for You?

**Comment by pec27** [comment]
Hi. The visualisation was a separate script (essentially a per-pixel raytracing onto a sphere, then transform to long & lat and reading from the map). The exponent of lambda depends on the length of the coefficient array, i.e. (a, b, c, d,...) corresponds to 1/C_l = a + b * l(l+1) + c*l^2 (l+1)^2 + d*l^3 (l+1)^3 + .... Hope that helps.
